# Generated by Django 6.1 on 2026-08-15 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cabin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(unique=True, verbose_name='Número de cabaña')),
                ('gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, verbose_name='Género')),
                ('age_range', models.CharField(blank=True, max_length=60, verbose_name='Rango de edad')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Ubicación')),
            ],
            options={
                'verbose_name': 'Cabaña',
                'verbose_name_plural': 'Cabañas',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='Nombre completo')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Teléfono')),
                ('role', models.CharField(choices=[('camper', 'Acampante'), ('leader', 'Líder de cabaña')], default='camper', max_length=10, verbose_name='Rol')),
                ('gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, verbose_name='Género')),
                ('is_active', models.BooleanField(default=True, verbose_name='Asiste')),
                ('cabin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='members', to='core.cabin', verbose_name='Cabaña')),
            ],
            options={
                'verbose_name': 'Acampante/Líder',
                'verbose_name_plural': 'Acampantes y Líderes',
                'ordering': ['cabin', 'role', 'full_name'],
                'constraints': [models.UniqueConstraint(fields=('cabin', 'full_name', 'role'), name='unique_cabin_name_role')],
            },
        ),
    ]
