# Generated by Django 6.1 on 2026-08-16 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='Desafío')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('cabin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to='core.cabin', verbose_name='Cabaña')),
            ],
            options={
                'verbose_name': 'Desafío',
                'verbose_name_plural': 'Desafíos',
                'ordering': ['-created_at'],
            },
        ),
    ]
