# Generated by Django 6.1 on 2026-08-18 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_challenge_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='must_change_password',
            field=models.BooleanField(default=True, verbose_name='Debe cambiar contraseña'),
        ),
    ]
