# Generated by Django 6.1 on 2026-08-19 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_member_must_change_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='duration_days',
            field=models.PositiveSmallIntegerField(choices=[(5, '5 días'), (10, '10 días'), (20, '20 días'), (30, '1 mes')], default=30, verbose_name='Duración (días)'),
        ),
    ]
