# Generated by Django 6.1 on 2026-08-19 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_challenge_duration_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='profile_image',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Imagen de perfil'),
        ),
    ]
