# Generated by Django 6.1 on 2026-08-26 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_member_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AddField(
            model_name='member',
            name='church',
            field=models.CharField(blank=True, max_length=150, verbose_name='Iglesia'),
        ),
    ]
