# Generated by Django 6.1 on 2026-08-28 03:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_add_profile_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitionPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=50, verbose_name='Equipo de color')),
                ('filename', models.CharField(max_length=255, verbose_name='Archivo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
            ],
            options={
                'verbose_name': 'Foto de competencia',
                'verbose_name_plural': 'Fotos de competencias',
                'ordering': ['-id'],
                'constraints': [models.UniqueConstraint(fields=('color', 'filename'), name='unique_color_filename')],
            },
        ),
        migrations.CreateModel(
            name='PhotoComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=200, verbose_name='Comentario')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Enviado')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.competitionphoto', verbose_name='Foto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_comments', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Comentario',
                'verbose_name_plural': 'Comentarios',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PhotoReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction', models.CharField(choices=[('like', '👍'), ('heart', '❤️'), ('cry', '😭'), ('llama', '🦙')], max_length=10, verbose_name='Reacción')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='core.competitionphoto', verbose_name='Foto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_reactions', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Reacción',
                'verbose_name_plural': 'Reacciones',
                'constraints': [models.UniqueConstraint(fields=('photo', 'user'), name='unique_photo_user_reaction')],
            },
        ),
    ]
