# Generated by Django 6.1 on 2026-08-28 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_competitionphoto_photocomment_photoreaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoreaction',
            name='reaction',
            field=models.CharField(choices=[('like', '👍'), ('heart', '❤️'), ('cry', '😭'), ('llama', '🦙'), ('fire', '🔥')], max_length=10, verbose_name='Reacción'),
        ),
    ]
