# Generated by Django 6.1 on 2026-08-28 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_photoreaction_reaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='photocomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='core.photocomment', verbose_name='Comentario padre'),
        ),
    ]
