# Generated by Django 6.1 on 2026-09-02 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_challengecomment_challengecommentreaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='BibleBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(unique=True, verbose_name='Número del libro')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('abbreviation', models.CharField(blank=True, default='', max_length=10, verbose_name='Abreviatura')),
                ('testament', models.CharField(choices=[('AT', 'Antiguo Testamento'), ('NT', 'Nuevo Testamento')], max_length=2, verbose_name='Testamento')),
                ('total_chapters', models.PositiveSmallIntegerField(default=0, verbose_name='Total de capítulos')),
            ],
            options={
                'verbose_name': 'Libro de la Biblia',
                'verbose_name_plural': 'Libros de la Biblia',
                'ordering': ['number'],
            },
        ),
        migrations.AddField(
            model_name='challenge',
            name='chapter_end',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Capítulo final'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='chapter_start',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Capítulo inicial'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='has_reading',
            field=models.BooleanField(default=False, verbose_name='Incluye lectura bíblica'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='bible_book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='challenges', to='core.biblebook', verbose_name='Libro de la Biblia'),
        ),
        migrations.CreateModel(
            name='BibleVerse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.PositiveSmallIntegerField(verbose_name='Capítulo')),
                ('verse', models.PositiveSmallIntegerField(verbose_name='Versículo')),
                ('text', models.TextField(verbose_name='Texto')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verses', to='core.biblebook', verbose_name='Libro')),
            ],
            options={
                'verbose_name': 'Versículo',
                'verbose_name_plural': 'Versículos',
                'ordering': ['book', 'chapter', 'verse'],
                'constraints': [models.UniqueConstraint(fields=('book', 'chapter', 'verse'), name='unique_book_chapter_verse')],
            },
        ),
    ]
